### ISSUE TITLE
Tags on unsupported resources are counted as change

### ISSUE THREAD

**Issue by slavizh** [Azure/arm-template-whatif#26]
## Describe the noise

Certain resources do not support tags but you can specify the tags property in the template and the deployment will run fine. We do that to future proof when at some point may be the resource starts supporting tags and because ARM allows it. This is counted as change by What-If unfortunately. 

Example:

```
  ~ Microsoft.Insights/diagnosticSettings/subscriptionLogsToLogAnalytics-vuwqlkipg5ibm [2017-05-01-preview]
    + tags:
 
        version: "1.0.0.0"
 

```

More information is provided by e-mail.
**Resource type** (i.e. Microsoft.Storage/storageAccounts)

**apiVersion** (i.e. 2019-04-01)

**Client (PowerShell, Azure CLI, or API)**

**Relevant ARM Template code (we only need the resource object for the above `resourceType` and `apiVersion`, but if it's easier you can include the entire template**

**Expected response (i.e. "I expected no noise since the template has not been modified since the resources were deployed)**

**Current (noisy) response (either include a screenshot of the what-if output, or copy/paste the text)**

**Additional context**

**Comment by majastrz** [comment]
We have checked in a fix for this behavior to an internal repo and it is awaiting deployment. If diagnosticSettings or other resource types with similar behavior support tags in the future, what-if will adjust after the behavior change is detected. (I will update this issue once the fix is deployed.)

**Comment by alex-frankel** [comment]
The fix should be deployed. Please reopen the issue if you still see this noise.

**Comment by slavizh** [comment]
Reported in another e-mail that I still see if for resource 


  ~ Microsoft.OperationalInsights/workspaces/lz-monitoring-core-acceptance-stan34/tables/Perf [2017-04-26-preview]
    + tags:

        version: "1.0.0.0"

**Comment by majastrz** [comment]
Thanks for letting us know. We will investigate.

**Comment by shenglol** [comment]
I think this is now tracked by https://github.com/Azure/arm-template-whatif/issues/96.
